##################################################
# Default makefile
# Redirect make to target makefile
##################################################

all:
	make -f Makefiletop.mk all
clean:
	make -f Makefiletop.mk clean
.PHONY: 
	make -f Makefiletop.mk all clean
